services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Kutay.21
      POSTGRES_DATABASE: crypto_database
    ports:
      - "5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: python FlaskBinance.py
    volumes:
      - .:/app
    ports:
      - "5001:5001"  # Run the Flask app on port 5000, expose it to the outside world on port 5001
    depends_on:
      - db
    

volumes:
  postgres_data:
